# Generated by Django 6.0.2 on 2026-03-14 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('package', 'Package & Pricing'), ('policy', 'Booking Policy'), ('script', 'Response Script'), ('objection', 'Objection Handling'), ('faq', 'FAQ'), ('location', 'Studio Location & Hours'), ('bilingual', 'Bilingual Phrases'), ('success_pattern', 'Success Pattern')], db_index=True, max_length=30)),
                ('content', models.TextField()),
                ('language', models.CharField(default='en', help_text='en | rw | both', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('messages_summarized', models.PositiveSmallIntegerField(help_text='Number of messages compressed into this summary')),
                ('tokens_saved', models.PositiveIntegerField(default=0, help_text='Estimated tokens saved by summarization')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='conversations.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveSmallIntegerField(help_text='Order within document')),
                ('content', models.TextField()),
                ('embedding', models.JSONField(blank=True, help_text='Float list from embedding model (text-embedding-3-small)', null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=60)),
                ('token_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.knowledgedocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
    ]
