# Generated by Django 6.0.2 on 2026-05-13 20:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_instagramconversation_token_budget_and_more'),
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('messages_summarized', models.PositiveSmallIntegerField()),
                ('tokens_saved', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='instagram.instagramconversation')),
            ],
        ),
    ]
