# Generated by Django 6.0.2 on 2026-05-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammessage',
            name='model_used',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='tokens_input',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='tokens_output',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
