# Generated by Django 6.0.2 on 2026-05-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_instagramapprovalqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramconversation',
            name='token_budget',
            field=models.PositiveIntegerField(default=20000, help_text='Max tokens before forcing human takeover'),
        ),
        migrations.AddField(
            model_name='instagramconversation',
            name='tokens_used',
            field=models.PositiveIntegerField(default=0, help_text='Total tokens used in this conversation'),
        ),
    ]
