# Generated by Django 6.0.2 on 2026-03-14 13:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('booked', 'Booked'), ('session_done', 'Session Done'), ('returning', 'Returning'), ('cold', 'Cold')], db_index=True, default='new', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('rw', 'Kinyarwanda')], default='en', max_length=5)),
                ('referral_source', models.CharField(blank=True, help_text='ad | story_reply | manual | outbound | birthday', max_length=50)),
                ('satisfaction_score', models.PositiveSmallIntegerField(blank=True, help_text='1-5 from post-session feedback', null=True)),
                ('total_sessions', models.PositiveSmallIntegerField(default=0)),
                ('total_spent_rwf', models.PositiveIntegerField(default=0)),
                ('lifetime_tokens_used', models.PositiveIntegerField(default=0, help_text='Running total of Claude tokens spent on this client')),
                ('is_opted_out', models.BooleanField(db_index=True, default=False)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('first_contact', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_contact'],
                'indexes': [models.Index(fields=['status', 'last_contact'], name='clients_cli_status_4b8e97_idx')],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('birthday', models.DateField(blank=True, db_index=True, null=True)),
                ('birthday_wish_sent_year', models.PositiveSmallIntegerField(blank=True, help_text='Year when last birthday wish was sent (prevents duplicates)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='clients.client')),
            ],
            options={
                'verbose_name_plural': 'children',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('human', 'Human'), ('ai_flagged', 'AI Flagged (Pending Review)')], default='human', max_length=20)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('entry', 'Entry'), ('booking', 'Booking'), ('sales_resistance', 'Sales Resistance'), ('preparation', 'Preparation'), ('delivery', 'Delivery'), ('feedback', 'Feedback'), ('complete', 'Complete'), ('paused', 'Paused (Human Takeover)')], default='entry', max_length=30)),
                ('step', models.CharField(choices=[('greeting', 'Greeting'), ('identify_type', 'Identify Client Type'), ('collect_child_info', 'Collect Child Info'), ('package_presentation', 'Package Presentation'), ('date_coordination', 'Date Coordination'), ('payment_confirmation', 'Payment Confirmation'), ('objection_handling', 'Objection Handling'), ('follow_up', 'Follow Up'), ('session_confirmation', 'Session Confirmation'), ('preparation_checklist', 'Preparation Checklist'), ('day_of_welcome', 'Day-of Welcome'), ('thank_you', 'Thank You'), ('photo_delivery', 'Photo Delivery'), ('feedback_request', 'Feedback Request'), ('appreciation', 'Appreciation')], default='greeting', max_length=40)),
                ('heat_score', models.PositiveSmallIntegerField(default=50)),
                ('detected_objection', models.CharField(blank=True, help_text='price | timing | authority | passive | competitor', max_length=50)),
                ('objection_count', models.PositiveSmallIntegerField(default=0)),
                ('next_followup_at', models.DateTimeField(blank=True, null=True)),
                ('followup_count', models.PositiveSmallIntegerField(default=0)),
                ('human_takeover', models.BooleanField(default=False, help_text='When True, AI is silenced and human handles this client')),
                ('takeover_reason', models.CharField(blank=True, max_length=200)),
                ('selected_package', models.CharField(blank=True, max_length=100)),
                ('session_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey_state', to='clients.client')),
            ],
            options={
                'indexes': [models.Index(fields=['phase', 'heat_score'], name='clients_jou_phase_6fe326_idx'), models.Index(fields=['next_followup_at'], name='clients_jou_next_fo_bbb0bf_idx'), models.Index(fields=['human_takeover'], name='clients_jou_human_t_68a19f_idx')],
            },
        ),
    ]
