# Generated by Django 6.0.2 on 2026-03-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeystate',
            name='discovery_state',
            field=models.JSONField(blank=True, default=dict, help_text='{"session_type":"studio","frames":true,"cake":false,"video":null}'),
        ),
        migrations.AddField(
            model_name='journeystate',
            name='flow_mode',
            field=models.CharField(blank=True, default='', help_text="booking | prices | question | '' (aucun flow actif)", max_length=20),
        ),
    ]
