# Generated by Django 6.0.2 on 2026-03-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_journeystate_discovery_state_journeystate_flow_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystate',
            name='flow_mode',
            field=models.CharField(blank=True, default='', help_text="booking | prices | question | '' (aucun flow actif)", max_length=50),
        ),
    ]
