# Generated by Django 6.0.2 on 2026-03-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_journeystate_flow_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='language_locked',
            field=models.BooleanField(default=False),
        ),
    ]
