# Generated by Django 6.0.2 on 2026-05-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_language_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ig_user_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Instagram sender ID for DM bot', max_length=50),
        ),
    ]
