# Generated by Django 6.0.2 on 2026-03-14 13:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_status', models.CharField(choices=[('open', 'Open (within 24h)'), ('closed', 'Closed (24h expired)')], default='open', max_length=10)),
                ('window_expires_at', models.DateTimeField(blank=True, null=True)),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Total Claude tokens used in this conversation')),
                ('token_budget', models.PositiveIntegerField(default=20000, help_text='Max tokens before forcing human takeover')),
                ('entry_phase', models.CharField(blank=True, max_length=30)),
                ('entry_heat', models.PositiveSmallIntegerField(default=50)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='clients.client')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('send_bonus', 'Send Bonus Offer'), ('send_message', 'Send AI Draft Message'), ('package_adjustment', 'Package Adjustment'), ('escalate', 'Escalate to Human'), ('send_followup', 'Send Follow-up')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired (auto-archived)')], db_index=True, default='pending', max_length=10)),
                ('ai_suggestion', models.TextField(help_text='What AI wants to send/do')),
                ('ai_reasoning', models.TextField(blank=True, help_text='Why AI is suggesting this')),
                ('heat_score_at_suggestion', models.PositiveSmallIntegerField(default=50)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_items', to='clients.client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_items', to='conversations.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('reply_speed', 'Reply Speed'), ('message_length', 'Message Length'), ('question_depth', 'Question Depth'), ('emotional_tone', 'Emotional Tone'), ('engagement_pattern', 'Engagement Pattern'), ('manual_override', 'Manual Override')], max_length=30)),
                ('delta', models.SmallIntegerField(help_text='Score change: +10, -5, etc.')),
                ('score_before', models.PositiveSmallIntegerField()),
                ('score_after', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heat_events', to='clients.client')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heat_events', to='conversations.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_message_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (client → us)'), ('outbound', 'Outbound (us → client)')], max_length=10)),
                ('status', models.CharField(choices=[('received', 'Received'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='received', max_length=15)),
                ('content', models.TextField()),
                ('msg_type', models.CharField(default='text', help_text='text | image | audio | interactive | template', max_length=20)),
                ('generated_by_ai', models.BooleanField(default=False)),
                ('model_used', models.CharField(blank=True, max_length=60)),
                ('tokens_input', models.PositiveIntegerField(default=0)),
                ('tokens_output', models.PositiveIntegerField(default=0)),
                ('approved_by_human', models.BooleanField(blank=True, help_text='None=auto-sent, True=human approved, False=human rejected', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='clients.client')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('birthday_wish', 'Birthday Wish'), ('birthday_reminder', 'Birthday Reminder (Outbound)'), ('followup', 'Follow-up'), ('session_reminder', 'Session Reminder'), ('day_of_welcome', 'Day-of Welcome'), ('feedback_request', 'Feedback Request')], max_length=30)),
                ('content', models.TextField(blank=True, help_text='Pre-rendered content or template name')),
                ('language', models.CharField(default='en', max_length=5)),
                ('send_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=15)),
                ('dedup_key', models.CharField(help_text='e.g. birthday_wish:client_id:2025 — prevents duplicates', max_length=100, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='clients.client')),
            ],
            options={
                'ordering': ['send_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['client', 'window_status'], name='conversatio_client__be51d3_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['window_expires_at'], name='conversatio_window__3179f8_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalqueue',
            index=models.Index(fields=['status', 'expires_at'], name='conversatio_status_e30f17_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalqueue',
            index=models.Index(fields=['client', 'status'], name='conversatio_client__f31ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'timestamp'], name='conversatio_convers_70c0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['direction', 'status'], name='conversatio_directi_59e1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledmessage',
            index=models.Index(fields=['status', 'send_at'], name='conversatio_status_7330f3_idx'),
        ),
    ]
