# Generated by Django 6.0.2 on 2026-03-24 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('child_name', models.CharField(max_length=100)),
                ('child_gender', models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('other', 'Other')], max_length=10)),
                ('child_age', models.CharField(help_text="e.g. '2 years', '6 months'", max_length=20)),
                ('child_birthday', models.DateField(blank=True, help_text='Used for auto-scheduling birthday messages', null=True)),
                ('occasion', models.CharField(choices=[('birthday', 'Birthday'), ('milestone', 'Milestone'), ('family', 'Family Portrait'), ('graduation', 'Graduation'), ('other', 'Other')], default='birthday', max_length=20)),
                ('package', models.CharField(choices=[('starter', 'Starter Package'), ('silver', 'Silver Package'), ('gold', 'Gold Package')], max_length=10)),
                ('extras', models.CharField(blank=True, help_text='e.g. Frames, Cake, Video', max_length=200)),
                ('preferred_outfit', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('booking_day', models.DateField()),
                ('booking_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['booking_day', 'booking_time'],
                'indexes': [models.Index(fields=['booking_day'], name='conversatio_booking_7acfb7_idx'), models.Index(fields=['phone'], name='conversatio_phone_260462_idx')],
            },
        ),
    ]
