# Generated by Django 6.0.2 on 2026-03-29 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_journeystate_flow_mode'),
        ('conversations', '0002_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='child_age',
        ),
        migrations.AddField(
            model_name='booking',
            name='photo_type',
            field=models.CharField(blank=True, choices=[('child', 'Child Photoshoot'), ('family', 'Family Photoshoot')], max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='child_birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='child_gender',
            field=models.CharField(blank=True, choices=[('boy', 'Boy'), ('girl', 'Girl'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='child_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='extras',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='occasion',
            field=models.CharField(choices=[('child_celebration', "Children's Celebration"), ('other', 'Other')], default='child_celebration', max_length=25),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.CharField(choices=[('starter', 'Starter Package'), ('silver', 'Silver Package'), ('gold', 'Gold Package'), ('premium', 'Premium Package')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['child_name'], name='conversatio_child_n_0998b1_idx'),
        ),
    ]
