# Generated by Django 6.0.2 on 2026-04-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_remove_booking_child_age_booking_photo_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_filename',
            field=models.CharField(blank=True, default='', help_text='Nom du fichier original (pour documents)', max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='media_mime_type',
            field=models.CharField(blank=True, default='', help_text='MIME type: image/jpeg, audio/ogg, application/pdf...', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.CharField(blank=True, default='', help_text='URL locale ou S3 du fichier media (image, audio, doc)', max_length=500),
        ),
    ]
